version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@dabliw
      POSTGRES_DB: dabliw-api
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres